/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import { Montserrat } from "next/font/google";
import { Footer } from "@/components/footer";

export const metadata: Metadata = {
  title: "Doña Leche",
  description: "Generated by create next app",
};

const font = Montserrat({ subsets: ["latin"] });

const TEXT_CHAT = "¡Hola! Quisiera realizar un pedido por favor.";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="donaleche/Logo_Dona_Leche_85x.webp"
          type="image/x-icon"
        />
      </head>
      <body className={font.className + ` antialiased`}>
        <div className="fixed z-50 bottom-0 right-0">
          <div className="w-20 h-20 flex items-center justify-center">
            <a
              href={`https://wa.me/573212138319?text=${TEXT_CHAT}`}
              target="_blank"
              rel="noopener noreferrer"
            >
              <img
                className="w-12 cursor-pointer animate-bounce"
                src="/donaleche/whatsapp.svg"
                alt="Doña leche whatsapp"
              />
            </a>
          </div>
        </div>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
